# CelFlow Central AI Brain Configuration
# Configuration for the central AI system that coordinates all agents

# Model Configuration
model:
  provider: "ollama"  # ollama, openai, anthropic
  model_name: "llama3.2:3b"  # Lightweight model for local processing
  temperature: 0.7
  max_tokens: 2048
  context_window: 8192

# Central Brain Settings
central_brain:
  enabled: true
  learning_rate: 0.01
  memory_consolidation_interval: 3600  # seconds
  pattern_recognition_threshold: 0.75
  decision_confidence_threshold: 0.8
  
# Agent Orchestration
orchestration:
  max_concurrent_agents: 10
  agent_spawn_threshold: 0.85
  agent_termination_threshold: 0.2
  resource_allocation_strategy: "adaptive"  # fixed, adaptive, competitive
  
# Learning and Adaptation
learning:
  meta_learning_enabled: true
  pattern_evolution_rate: 0.05
  feedback_integration_weight: 0.3
  experience_replay_enabled: true
  experience_buffer_size: 10000
  
# System Integration
integration:
  tray_integration: true
  voice_interface: false
  web_dashboard: true
  api_server: false
  
# Performance and Resources
performance:
  max_memory_mb: 1024
  max_cpu_percent: 25
  batch_processing_size: 100
  async_processing: true
  
# Privacy and Security
privacy:
  local_processing_only: true
  data_encryption: true
  sensitive_data_filtering: true
  audit_logging: true

# Logging and monitoring
logging:
  level: "INFO"
  ai_interactions: true
  performance_metrics: true
  error_tracking: true 